#!/bin/bash

# https://betterdiscord.app/Addon/GetApprovedAddons?type=theme&filter=&page=1&pages=2&sort=popular&sortDirection=&tags=%5B%5D


bd_remote_install() {
  curl -LSso "$bd_remote_dir/$bd_remote_asar" --create-dirs \
      "$bd_remote_url/$bd_remote_asar"
  if [[ "$bd_remote_dir/$bd_remote_asar" != "$bd_asar" ]]; then
    install -Dm 644 "$bd_remote_dir/$bd_remote_asar" "$bd_asar"
  fi
}
